set(WOLFSSL_VERSION "v5.9.2-stable")
set(WOLFSSL_DIR "${CMAKE_SOURCE_DIR}/vendor/wolfssl")
set(WOLFSSL_DOWNLOAD "https://github.com/wolfSSL/wolfssl/archive/refs/tags/${WOLFSSL_VERSION}.tar.gz")
set(WOLFSSL_ASIO yes CACHE STRING "" FORCE)
set(WOLFSSL_ALT_CERT_CHAINS yes CACHE STRING "" FORCE)
set(WOLFSSL_EXAMPLES no CACHE STRING "" FORCE)
set(WOLFSSL_CRYPT_TESTS no CACHE STRING "" FORCE)
set(WOLFSSL_INSTALL no CACHE STRING "" FORCE)
haio_fetch(wolfssl "${WOLFSSL_DOWNLOAD}" "${WOLFSSL_DIR}" CMakeLists.txt)
add_subdirectory("${WOLFSSL_DIR}" "${CMAKE_BINARY_DIR}/wolfssl" EXCLUDE_FROM_ALL)

include("${CMAKE_CURRENT_LIST_DIR}/../cmake/zlib-ng.cmake")

set(HAIO_TLS_DEFINITIONS
    BOOST_ASIO_USE_WOLFSSL OPENSSL_ALL OPENSSL_EXTRA HAVE_EX_DATA
    WOLFSSL_KEY_GEN HAVE_OCSP OPENSSL_NO_SSL2 OPENSSL_NO_SSL3)

target_link_libraries(${PROJECT_NAME} PRIVATE wolfssl)

target_compile_definitions(${PROJECT_NAME} PRIVATE
    BOOST_ASIO_USE_WOLFSSL OPENSSL_ALL OPENSSL_EXTRA HAVE_EX_DATA
    WOLFSSL_KEY_GEN HAVE_OCSP OPENSSL_NO_SSL2 OPENSSL_NO_SSL3
)