# barcodes and qr codes are painted with zint, compiled into the library rather than
# linked, and only as much of it as the brushes use: the symbologies below, and none
# of zint's own rendering or file writing -- the brushes read its modules and paint
# them the way every other brush paints.
#
#   code:  UPC-A, EAN-8, EAN-13, Code 39, Codabar, Code 128
#   qr:    QR Code, Data Matrix
#
# zint's library.c dispatches to every symbology it knows, so the ones left out are
# stubbed: each prototype library.c declares that no source here defines becomes a
# function that refuses. the stubs are read off library.c itself at configure time,
# so a new zint that adds a symbology still links, and says no to it.
#
# expects: haio_fetch
# appends: HAIO_GENERATORS_OFF when switched off, which scaffold.cmake leaves out

option(HAIO_USE_ZINT "paint barcodes and qr codes with zint" ON)

set(HAIO_ZINT_BRUSHES
    "${CMAKE_SOURCE_DIR}/library/backend/codecs/generators/code"
    "${CMAKE_SOURCE_DIR}/library/backend/codecs/generators/qr"
)

if(NOT HAIO_USE_ZINT)
    foreach(dir IN LISTS HAIO_ZINT_BRUSHES)
        file(GLOB_RECURSE sources CONFIGURE_DEPENDS "${dir}/*.cpp")
        # already handed to the executable by the time this runs, so they are
        # switched off rather than taken away
        set_source_files_properties(${sources} PROPERTIES HEADER_FILE_ONLY ON)
        list(APPEND HAIO_GENERATORS_OFF ${sources})
    endforeach()
    return()
endif()

set(ZINT_VERSION "2.15.0")
set(ZINT_DIR "${CMAKE_SOURCE_DIR}/vendor/zint")
set(ZINT_DOWNLOAD "https://github.com/zint/zint/archive/refs/tags/${ZINT_VERSION}.tar.gz")
haio_fetch(zint "${ZINT_DOWNLOAD}" "${ZINT_DIR}" backend/zint.h)

set(ZINT_BACKEND "${ZINT_DIR}/backend")
set(ZINT_SOURCES "")
foreach(name
        library common eci reedsol gs1   # what every symbology below leans on
        upcean                           # UPC-A, EAN-8, EAN-13
        code                             # Code 39
        codabar                          # Codabar
        code128                          # Code 128
        qr                               # QR Code
        dmatrix)                         # Data Matrix
    list(APPEND ZINT_SOURCES "${ZINT_BACKEND}/${name}.c")
endforeach()

# every symbology some source here defines, read off its definitions
set(ZINT_DEFINED "")
foreach(source IN LISTS ZINT_SOURCES)
    file(READ "${source}" text)
    string(REGEX MATCHALL "\nINTERNAL (int|void) [a-z0-9_]+\\([^;{]*\\)[ \t\r\n]*{" definitions "${text}")
    foreach(definition IN LISTS definitions)
        string(REGEX REPLACE "^\nINTERNAL (int|void) ([a-z0-9_]+)\\(.*" "\\2" name "${definition}")
        list(APPEND ZINT_DEFINED "${name}")
    endforeach()
endforeach()

# and every one library.c declares, which is every one it may dispatch to
file(READ "${ZINT_BACKEND}/library.c" library)
string(REGEX MATCHALL "\nINTERNAL (int|void) [a-z0-9_]+\\(struct zint_symbol \\*symbol[^)]*\\)" prototypes "${library}")

set(ZINT_STUBS "/* generated by cmake/zint.cmake from library.c -- do not edit */\n#include <string.h>\n#include \"common.h\"\n")
foreach(prototype IN LISTS prototypes)
    string(REGEX REPLACE "^\nINTERNAL (int|void) ([a-z0-9_]+)\\((.*)\\)$" "\\1" returns "${prototype}")
    string(REGEX REPLACE "^\nINTERNAL (int|void) ([a-z0-9_]+)\\((.*)\\)$" "\\2" name "${prototype}")
    string(REGEX REPLACE "^\nINTERNAL (int|void) ([a-z0-9_]+)\\((.*)\\)$" "\\3" arguments "${prototype}")
    if(name IN_LIST ZINT_DEFINED)
        continue()
    endif()
    if(returns STREQUAL "void")
        string(APPEND ZINT_STUBS "INTERNAL void ${name}(${arguments}) { (void) symbol; }\n")
    else()
        string(APPEND ZINT_STUBS "INTERNAL int ${name}(${arguments}) {\n"
            "    strcpy(symbol->errtxt, \"left out of this build of haio\");\n"
            "    return ZINT_ERROR_INVALID_OPTION;\n}\n")
    endif()
endforeach()

# written only when it changes, so a reconfigure does not rebuild zint for nothing
file(CONFIGURE OUTPUT "${CMAKE_BINARY_DIR}/zint/stubs.c" CONTENT "${ZINT_STUBS}" @ONLY)

add_library(zint STATIC ${ZINT_SOURCES} "${CMAKE_BINARY_DIR}/zint/stubs.c")
target_include_directories(zint PUBLIC "${ZINT_BACKEND}")
target_link_libraries(${PROJECT_NAME} PRIVATE zint)
